services:

  backend:
    image: backend
    pull_policy: never
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runner
    ports:
      - 8000:8000

  frontend:
    image: frontend
    pull_policy: never
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80