services:

  backend:
    image: backend
    pull_policy: never
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runner
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env

  frontend:
    image: frontend
    pull_policy: never
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80

  mongodb:
    image: mongo:7.0.12
    container_name: mongodb
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    env_file:
      - ./mongodb/.env
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: admin12345

volumes:
  mongodb: